-- this view is used into kaartdijin boodja to spatial support system to provide a live feed the spatial support system

CREATE VIEW public.bushfirelist_latest AS
SELECT bfrs_bushfirelist_v.id,
bfrs_bushfirelist_v.origin_point,
bfrs_bushfirelist_v.fire_boundary,
bfrs_bushfirelist_v.fb_validation_req,
bfrs_bushfirelist_v.created,
bfrs_bushfirelist_v.modified,
bfrs_bushfirelist_v.name,
bfrs_bushfirelist_v.fire_number,
bfrs_bushfirelist_v.year,
bfrs_bushfirelist_v.reporting_year,
bfrs_bushfirelist_v.prob_fire_level,
bfrs_bushfirelist_v.max_fire_level,
bfrs_bushfirelist_v.media_alert_req,
bfrs_bushfirelist_v.park_trail_impacted,
bfrs_bushfirelist_v.cause_state,
bfrs_bushfirelist_v.other_cause,
bfrs_bushfirelist_v.dfes_incident_no,
bfrs_bushfirelist_v.job_code,
bfrs_bushfirelist_v.fire_position,
bfrs_bushfirelist_v.sss_id,
bfrs_bushfirelist_v.fire_position_override,
bfrs_bushfirelist_v.fire_not_found,
bfrs_bushfirelist_v.other_info,
bfrs_bushfirelist_v.init_authorised_date,
bfrs_bushfirelist_v.dispatch_pw,
bfrs_bushfirelist_v.dispatch_aerial,
bfrs_bushfirelist_v.dispatch_pw_date,
bfrs_bushfirelist_v.dispatch_aerial_date,
bfrs_bushfirelist_v.fire_detected_date,
bfrs_bushfirelist_v.fire_detected_or_created,
bfrs_bushfirelist_v.fire_contained_date,
bfrs_bushfirelist_v.fire_controlled_date,
bfrs_bushfirelist_v.fire_safe_date,
bfrs_bushfirelist_v.other_first_attack,
bfrs_bushfirelist_v.other_initial_control,
bfrs_bushfirelist_v.other_final_control,
bfrs_bushfirelist_v.arson_squad_notified,
bfrs_bushfirelist_v.investigation_req,
bfrs_bushfirelist_v.offence_no,
bfrs_bushfirelist_v.initial_area,
bfrs_bushfirelist_v.area,
bfrs_bushfirelist_v.area_limit,
bfrs_bushfirelist_v.initial_area_unknown,
bfrs_bushfirelist_v.authorised_date,
bfrs_bushfirelist_v.report_status,
bfrs_bushfirelist_v.archive,
bfrs_bushfirelist_v.linked_bushfire_status,
bfrs_bushfirelist_v.linked_bushfire_number,
bfrs_bushfirelist_v.authorised_by_id,
bfrs_bushfirelist_v.cause_id,
bfrs_bushfirelist_v.creator_id,
bfrs_bushfirelist_v.district_id,
bfrs_bushfirelist_v.duty_officer_id,
bfrs_bushfirelist_v.field_officer_id,
bfrs_bushfirelist_v.final_control_id,
bfrs_bushfirelist_v.first_attack_id,
bfrs_bushfirelist_v.init_authorised_by_id,
bfrs_bushfirelist_v.initial_control_id,
bfrs_bushfirelist_v.modifier_id,
bfrs_bushfirelist_v.region_id,
bfrs_bushfirelist_v.tenure_id
FROM public.bfrs_bushfirelist_v
WHERE (((date_part('month'::text, now()) >= (7)::double precision) AND (bfrs_bushfirelist_v.fire_detected_or_created >= (concat((date_part('year'::text, now()) - (2)::double precision), '-07-01'))::date)) OR ((date_part('month'::text, now()) < (7)::double precision) AND (bfrs_bushfirelist_v.fire_detected_or_created >= (concat((date_part('year'::text, now()) - (3)::double precision), '-07-01'))::date)));