# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 02:32
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'Agency Name')),
                ('code', models.CharField(max_length=10, verbose_name=b'Agency Short Code')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AreaBurnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Area (ha)')),
            ],
        ),
        migrations.CreateModel(
            name='AreaBurntSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Area (ha)')),
                ('snapshot_type', models.PositiveSmallIntegerField(choices=[(1, b'Initial'), (2, b'Final')])),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_areaburntsnapshot_created', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_areaburntsnapshot_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bushfire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name=b'Fire Name')),
                ('year', models.PositiveSmallIntegerField(default=2017, verbose_name=b'Financial Year')),
                ('reporting_year', models.PositiveSmallIntegerField(blank=True, default=2017, verbose_name=b'Reporting Year')),
                ('prob_fire_level', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], null=True, verbose_name=b'Probable fire level')),
                ('max_fire_level', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], null=True, verbose_name=b'Maximum fire level')),
                ('media_alert_req', models.NullBooleanField(verbose_name=b'Media Alert Required')),
                ('park_trail_impacted', models.NullBooleanField(verbose_name=b'Park and/or trail potentially impacted')),
                ('cause_state', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Known'), (2, b'Possible')], null=True, verbose_name=b'Fire Cause State (Known/Possible)')),
                ('other_cause', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Other Fire Cause')),
                ('prescribed_burn_id', models.CharField(blank=True, max_length=7, null=True, verbose_name=b'Prescribed Burn ID')),
                ('other_tenure', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Private'), (2, b'Crown')], null=True, verbose_name=b'Tenure of ignition point (crown/private)')),
                ('dfes_incident_no', models.CharField(blank=True, max_length=32, null=True, verbose_name=b'DFES Fire Number')),
                ('job_code', models.CharField(blank=True, max_length=12, null=True, verbose_name=b'Job Code')),
                ('fire_position', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Position of Fire')),
                ('fire_position_override', models.BooleanField(default=False, verbose_name=b'SSS override')),
                ('origin_point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name=b'Point of Origin')),
                ('origin_point_mga', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Point of Origin (MGA)')),
                ('fire_boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text=b'Optional.', null=True, srid=4326)),
                ('fire_not_found', models.BooleanField(default=False)),
                ('fire_monitored_only', models.BooleanField(default=False)),
                ('final_fire_boundary', models.BooleanField(default=False)),
                ('fb_validation_req', models.NullBooleanField(verbose_name=b'Fire Boundary Validation Required?')),
                ('other_info', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'Other Information')),
                ('other_field_officer', models.CharField(blank=True, max_length=75, null=True, verbose_name=b'Other Field Officer Name')),
                ('other_field_officer_agency', models.CharField(blank=True, max_length=36, null=True, verbose_name=b'Other Field Officer Agency')),
                ('other_field_officer_phone', models.CharField(blank=True, max_length=24, null=True, verbose_name=b'Other Field Officer Phone')),
                ('init_authorised_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Initial Authorised Date')),
                ('dispatch_pw', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Yes'), (2, b'No')], null=True, verbose_name=b'P&W Resource dispatched')),
                ('dispatch_aerial', models.NullBooleanField(verbose_name=b'Aerial suppression dispatched')),
                ('dispatch_pw_date', models.DateTimeField(blank=True, null=True, verbose_name=b'P&W Resource dispatch date')),
                ('dispatch_aerial_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Aerial suppression dispatch date')),
                ('fire_detected_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Date and time fire detected')),
                ('fire_contained_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Date fire Contained')),
                ('fire_controlled_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Date fire Controlled')),
                ('fire_safe_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Date fire inactive')),
                ('other_first_attack', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Other Initial Attack Agency')),
                ('other_initial_control', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Other Initial Control Agency')),
                ('other_final_control', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Other Final Control Agency')),
                ('arson_squad_notified', models.NullBooleanField(verbose_name=b'Arson Squad Notified')),
                ('investigation_req', models.NullBooleanField(verbose_name=b'Investigation Required')),
                ('offence_no', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'Police Offence No.')),
                ('initial_area', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Area of fire at arrival (ha)')),
                ('initial_area_unknown', models.BooleanField(default=False)),
                ('area', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Final Fire Area (ha)')),
                ('area_limit', models.BooleanField(default=False, verbose_name=b'Area < 2ha')),
                ('other_area', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Other Area (ha)')),
                ('damage_unknown', models.BooleanField(default=False, verbose_name=b'Damages to report?')),
                ('injury_unknown', models.BooleanField(default=False, verbose_name=b'Injuries to report?')),
                ('authorised_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Authorised Date')),
                ('reviewed_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Reviewed Date')),
                ('report_status', models.PositiveSmallIntegerField(choices=[(1, b'Initial Fire Report'), (2, b'Notifications Submitted'), (3, b'Report Authorised'), (4, b'Reviewed'), (5, b'Invalidated'), (6, b'Outstanding Fires')], default=1, editable=False)),
                ('sss_data', models.TextField(blank=True, null=True, verbose_name=b'SSS REST Api Dict')),
                ('archive', models.BooleanField(default=False, verbose_name=b'Archive report')),
                ('invalid_details', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Reason for invalidating')),
                ('fire_number', models.CharField(max_length=15, unique=True, verbose_name=b'Fire Number')),
                ('sss_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name=b'Unique SSS ID')),
                ('authorised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfire_authorised_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Authorised By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BushfireSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name=b'Fire Name')),
                ('year', models.PositiveSmallIntegerField(default=2017, verbose_name=b'Financial Year')),
                ('reporting_year', models.PositiveSmallIntegerField(blank=True, default=2017, verbose_name=b'Reporting Year')),
                ('prob_fire_level', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], null=True, verbose_name=b'Probable fire level')),
                ('max_fire_level', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], null=True, verbose_name=b'Maximum fire level')),
                ('media_alert_req', models.NullBooleanField(verbose_name=b'Media Alert Required')),
                ('park_trail_impacted', models.NullBooleanField(verbose_name=b'Park and/or trail potentially impacted')),
                ('cause_state', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Known'), (2, b'Possible')], null=True, verbose_name=b'Fire Cause State (Known/Possible)')),
                ('other_cause', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Other Fire Cause')),
                ('prescribed_burn_id', models.CharField(blank=True, max_length=7, null=True, verbose_name=b'Prescribed Burn ID')),
                ('other_tenure', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Private'), (2, b'Crown')], null=True, verbose_name=b'Tenure of ignition point (crown/private)')),
                ('dfes_incident_no', models.CharField(blank=True, max_length=32, null=True, verbose_name=b'DFES Fire Number')),
                ('job_code', models.CharField(blank=True, max_length=12, null=True, verbose_name=b'Job Code')),
                ('fire_position', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Position of Fire')),
                ('fire_position_override', models.BooleanField(default=False, verbose_name=b'SSS override')),
                ('origin_point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name=b'Point of Origin')),
                ('origin_point_mga', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Point of Origin (MGA)')),
                ('fire_boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text=b'Optional.', null=True, srid=4326)),
                ('fire_not_found', models.BooleanField(default=False)),
                ('fire_monitored_only', models.BooleanField(default=False)),
                ('final_fire_boundary', models.BooleanField(default=False)),
                ('fb_validation_req', models.NullBooleanField(verbose_name=b'Fire Boundary Validation Required?')),
                ('other_info', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'Other Information')),
                ('other_field_officer', models.CharField(blank=True, max_length=75, null=True, verbose_name=b'Other Field Officer Name')),
                ('other_field_officer_agency', models.CharField(blank=True, max_length=36, null=True, verbose_name=b'Other Field Officer Agency')),
                ('other_field_officer_phone', models.CharField(blank=True, max_length=24, null=True, verbose_name=b'Other Field Officer Phone')),
                ('init_authorised_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Initial Authorised Date')),
                ('dispatch_pw', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Yes'), (2, b'No')], null=True, verbose_name=b'P&W Resource dispatched')),
                ('dispatch_aerial', models.NullBooleanField(verbose_name=b'Aerial suppression dispatched')),
                ('dispatch_pw_date', models.DateTimeField(blank=True, null=True, verbose_name=b'P&W Resource dispatch date')),
                ('dispatch_aerial_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Aerial suppression dispatch date')),
                ('fire_detected_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Date and time fire detected')),
                ('fire_contained_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Date fire Contained')),
                ('fire_controlled_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Date fire Controlled')),
                ('fire_safe_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Date fire inactive')),
                ('other_first_attack', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Other Initial Attack Agency')),
                ('other_initial_control', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Other Initial Control Agency')),
                ('other_final_control', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Other Final Control Agency')),
                ('arson_squad_notified', models.NullBooleanField(verbose_name=b'Arson Squad Notified')),
                ('investigation_req', models.NullBooleanField(verbose_name=b'Investigation Required')),
                ('offence_no', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'Police Offence No.')),
                ('initial_area', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Area of fire at arrival (ha)')),
                ('initial_area_unknown', models.BooleanField(default=False)),
                ('area', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Final Fire Area (ha)')),
                ('area_limit', models.BooleanField(default=False, verbose_name=b'Area < 2ha')),
                ('other_area', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Other Area (ha)')),
                ('damage_unknown', models.BooleanField(default=False, verbose_name=b'Damages to report?')),
                ('injury_unknown', models.BooleanField(default=False, verbose_name=b'Injuries to report?')),
                ('authorised_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Authorised Date')),
                ('reviewed_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Reviewed Date')),
                ('report_status', models.PositiveSmallIntegerField(choices=[(1, b'Initial Fire Report'), (2, b'Notifications Submitted'), (3, b'Report Authorised'), (4, b'Reviewed'), (5, b'Invalidated'), (6, b'Outstanding Fires')], default=1, editable=False)),
                ('sss_data', models.TextField(blank=True, null=True, verbose_name=b'SSS REST Api Dict')),
                ('archive', models.BooleanField(default=False, verbose_name=b'Archive report')),
                ('invalid_details', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Reason for invalidating')),
                ('fire_number', models.CharField(max_length=15, verbose_name=b'Fire Number')),
                ('sss_id', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Unique SSS ID')),
                ('snapshot_type', models.PositiveSmallIntegerField(choices=[(1, b'Initial'), (2, b'Final')])),
                ('action', models.CharField(max_length=50, verbose_name=b'Action Type')),
                ('authorised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfiresnapshot_authorised_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Authorised By')),
                ('bushfire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='bfrs.Bushfire')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('bushfire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='bfrs.Bushfire')),
            ],
        ),
        migrations.CreateModel(
            name='DamageSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('snapshot_type', models.PositiveSmallIntegerField(choices=[(1, b'Initial'), (2, b'Final')])),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_damagesnapshot_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'Damage Type')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=3)),
                ('archive_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('bushfire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='bfrs.Bushfire')),
            ],
        ),
        migrations.CreateModel(
            name='InjurySnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('snapshot_type', models.PositiveSmallIntegerField(choices=[(1, b'Initial'), (2, b'Final')])),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_injurysnapshot_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InjuryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name=b'Injury/Fatality Type')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field=b'region', chained_model_field=b'region', null=True, on_delete=django.db.models.deletion.CASCADE, to='bfrs.District')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tenure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name=b'Tenure category')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bfrs.Region'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='injurysnapshot',
            name='injury_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.InjuryType'),
        ),
        migrations.AddField(
            model_name='injurysnapshot',
            name='modifier',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_injurysnapshot_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='injurysnapshot',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injury_snapshot', to='bfrs.BushfireSnapshot'),
        ),
        migrations.AddField(
            model_name='injury',
            name='injury_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.InjuryType'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.Region'),
        ),
        migrations.AddField(
            model_name='damagesnapshot',
            name='damage_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.DamageType'),
        ),
        migrations.AddField(
            model_name='damagesnapshot',
            name='modifier',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_damagesnapshot_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='damagesnapshot',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_snapshot', to='bfrs.BushfireSnapshot'),
        ),
        migrations.AddField(
            model_name='damage',
            name='damage_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.DamageType'),
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bfrs.Cause', verbose_name=b'Fire Cause'),
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_bushfiresnapshot_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'region', chained_model_field=b'region', on_delete=django.db.models.deletion.CASCADE, to='bfrs.District', verbose_name=b'District'),
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='duty_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfiresnapshot_init_duty_officer', to=settings.AUTH_USER_MODEL, verbose_name=b'Duty Officer'),
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='field_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfiresnapshot_init_field_officer', to=settings.AUTH_USER_MODEL, verbose_name=b'Field Officer'),
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='final_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfiresnapshot_final_control', to='bfrs.Agency', verbose_name=b'Final Controlling Agency'),
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='first_attack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfiresnapshot_first_attack', to='bfrs.Agency', verbose_name=b'Initial Attack Agency'),
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='init_authorised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfiresnapshot_init_authorised_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Initial Authorised By'),
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='initial_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfiresnapshot_initial_control', to='bfrs.Agency', verbose_name=b'Initial Controlling Agency'),
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='modifier',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_bushfiresnapshot_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.Region', verbose_name=b'Region'),
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfiresnapshot_reviewed_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Reviewed By'),
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='tenure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bfrs.Tenure', verbose_name=b'Tenure of Ignition Point'),
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='valid_bushfire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfiresnapshot_invalidated', to='bfrs.BushfireSnapshot'),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bfrs.Cause', verbose_name=b'Fire Cause'),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_bushfire_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'region', chained_model_field=b'region', on_delete=django.db.models.deletion.CASCADE, to='bfrs.District', verbose_name=b'District'),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='duty_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfire_init_duty_officer', to=settings.AUTH_USER_MODEL, verbose_name=b'Duty Officer'),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='field_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfire_init_field_officer', to=settings.AUTH_USER_MODEL, verbose_name=b'Field Officer'),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='final_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfire_final_control', to='bfrs.Agency', verbose_name=b'Final Controlling Agency'),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='first_attack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfire_first_attack', to='bfrs.Agency', verbose_name=b'Initial Attack Agency'),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='init_authorised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfire_init_authorised_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Initial Authorised By'),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='initial_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfire_initial_control', to='bfrs.Agency', verbose_name=b'Initial Controlling Agency'),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='modifier',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_bushfire_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.Region', verbose_name=b'Region'),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfire_reviewed_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Reviewed By'),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='tenure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bfrs.Tenure', verbose_name=b'Tenure of Ignition Point'),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='valid_bushfire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfire_invalidated', to='bfrs.Bushfire'),
        ),
        migrations.AddField(
            model_name='areaburntsnapshot',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenures_burnt_snapshot', to='bfrs.BushfireSnapshot'),
        ),
        migrations.AddField(
            model_name='areaburntsnapshot',
            name='tenure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areaburntsnapshot_tenures', to='bfrs.Tenure'),
        ),
        migrations.AddField(
            model_name='areaburnt',
            name='bushfire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenures_burnt', to='bfrs.Bushfire'),
        ),
        migrations.AddField(
            model_name='areaburnt',
            name='tenure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areaburnt_tenures', to='bfrs.Tenure'),
        ),
        migrations.AlterUniqueTogether(
            name='injurysnapshot',
            unique_together=set([('injury_type', 'snapshot', 'snapshot_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='injury',
            unique_together=set([('bushfire', 'injury_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='damagesnapshot',
            unique_together=set([('damage_type', 'snapshot', 'snapshot_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='damage',
            unique_together=set([('bushfire', 'damage_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='areaburntsnapshot',
            unique_together=set([('tenure', 'snapshot', 'snapshot_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='areaburnt',
            unique_together=set([('bushfire', 'tenure')]),
        ),
    ]
