# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-02 03:12
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name=b'Activity Type')),
            ],
            options={
                'ordering': ['name'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='AerialForces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Fixed Wing'), (2, b'Helicopter')], null=True, verbose_name=b'Agency Name')),
                ('observer', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('transporter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ignition', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('water_bomber', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'Agency Name')),
                ('code', models.CharField(max_length=10, verbose_name=b'Agency Short Code')),
            ],
            options={
                'ordering': ['name'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='AreaBurnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='AttendingOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Bushfire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name=b'Fire Name')),
                ('incident_no', models.PositiveIntegerField(verbose_name=b'Fire Number')),
                ('dfes_incident_no', models.PositiveIntegerField(blank=True, null=True, verbose_name=b'DFES Fire Number')),
                ('job_code', models.PositiveIntegerField(blank=True, null=True, verbose_name=b'job Code')),
                ('potential_fire_level', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], null=True)),
                ('alert_level', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Emergency/Watch'), (2, b'Act/Advice')], null=True, verbose_name=b'Alert Level')),
                ('media_alert_req', models.BooleanField(default=False, verbose_name=b'Media Alert Required')),
                ('fire_position', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Position of Fire')),
                ('origin_point', django.contrib.gis.db.models.fields.PointField(blank=True, editable=False, help_text=b'Optional.', null=True, srid=4326)),
                ('fire_boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, editable=False, help_text=b'Optional.', null=True, srid=4326)),
                ('grid', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Lat/Long, MGA, FD Grid')),
                ('arrival_area', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Fire Area at Arrival (ha)')),
                ('fire_not_found', models.BooleanField(default=False)),
                ('assistance_req', models.BooleanField(default=False)),
                ('communications', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Communication')),
                ('other_info', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Other Information')),
                ('other_cause', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Other Cause')),
                ('init_authorised_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Authorised Date')),
                ('initial_snapshot', models.TextField(blank=True, null=True)),
                ('other_first_attack', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Other First Attack Agency')),
                ('other_initial_ctrl', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Other Initial Control Agency')),
                ('other_final_ctrl', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Other Final Control Agency')),
                ('max_fire_level', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], null=True)),
                ('arson_squad_notified', models.BooleanField(default=False, verbose_name=b'Arson Squad Notified')),
                ('offence_no', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'Police Offence No.')),
                ('final_area', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Final Fire Area (ha)')),
                ('authorised_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name=b'Authorised Date')),
                ('authorised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Authorised By')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='BushfireTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BushfireTest2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Fire Name')),
                ('incident_no', models.CharField(max_length=10, verbose_name=b'Fire Incident No.')),
                ('season', models.CharField(max_length=9)),
                ('dfes_incident_no', models.CharField(max_length=10, verbose_name=b'DFES Incident No.')),
                ('job_code', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'Job Code')),
                ('potential_fire_level', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('init_authorised_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name=b'Authorised Date')),
            ],
        ),
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('bushfire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bfrs.Bushfire')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_comment_created', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_comment_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('code', models.CharField(max_length=3)),
            ],
            options={
                'ordering': ['name'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=3)),
                ('archive_date', models.DateField(blank=True, help_text=b'Archive this District (prevent from creating new ePFPs)', null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FireBehaviour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Name/Description')),
                ('fuel_weight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fdi', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ros', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bushfire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_behaviour', to='bfrs.Bushfire')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='FrbEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='GroundForces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Initial DEC Dispatch'), (2, b'DEC Peak'), (3, b'Other Agencies Peak')], null=True, verbose_name=b'Agency Name')),
                ('persons', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pumpers', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('plant', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bushfire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ground_forces', to='bfrs.Bushfire')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='InvestigationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'Investigation Type')),
            ],
            options={
                'ordering': ['name'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protection', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name=b'Community Protection (%)')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Est. Cost of Damages ($)')),
                ('restricted_period', models.BooleanField(default=False)),
                ('prohibited_period', models.BooleanField(default=False)),
                ('bushfire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal', to='bfrs.Bushfire')),
                ('inv_undertaken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.InvestigationType', verbose_name=b'Investigation Undertaken')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='LegalResultType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'Legal Result Type')),
            ],
            options={
                'ordering': ['name'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'Organisation')),
            ],
            options={
                'ordering': ['name'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burn_id', models.CharField(max_length=7)),
            ],
            options={
                'ordering': ['burn_id'],
            },
        ),
        migrations.CreateModel(
            name='PriorityRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='PrivateDamage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('bushfire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_damages', to='bfrs.Bushfire')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='PrivateDamageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name=b'Private Damage Type')),
            ],
            options={
                'ordering': ['name'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field=b'region', chained_model_field=b'region', null=True, on_delete=django.db.models.deletion.CASCADE, to='bfrs.District')),
            ],
            options={
                'default_permissions': ('add', 'change', 'view'),
            },
        ),
        migrations.CreateModel(
            name='PublicDamage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=1, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Area (ha)')),
                ('bushfire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_damages', to='bfrs.Bushfire')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='PublicDamageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'Public Damage Type')),
            ],
            options={
                'ordering': ['name'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bushfire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='bfrs.Bushfire')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='ResponseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'Agency Name')),
            ],
            options={
                'ordering': ['name'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Tenure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='WaterBombEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.AddField(
            model_name='response',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.ResponseType'),
        ),
        migrations.AddField(
            model_name='publicdamage',
            name='damage_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.PublicDamageType'),
        ),
        migrations.AddField(
            model_name='publicdamage',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.FuelType'),
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bfrs.Region'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatedamage',
            name='damage_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.PrivateDamageType'),
        ),
        migrations.AddField(
            model_name='legal',
            name='legal_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.LegalResultType'),
        ),
        migrations.AddField(
            model_name='firebehaviour',
            name='fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_types_fire', to='bfrs.FuelType'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.Region'),
        ),
        migrations.AddField(
            model_name='bushfiretest2',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'region', chained_model_field=b'region', on_delete=django.db.models.deletion.CASCADE, to='bfrs.District'),
        ),
        migrations.AddField(
            model_name='bushfiretest2',
            name='init_authorised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Authorised By'),
        ),
        migrations.AddField(
            model_name='bushfiretest2',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.Region'),
        ),
        migrations.AddField(
            model_name='bushfiretest',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'region', chained_model_field=b'region', on_delete=django.db.models.deletion.CASCADE, to='bfrs.District'),
        ),
        migrations.AddField(
            model_name='bushfiretest',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.Region'),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bfrs.Cause'),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_bushfire_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'region', chained_model_field=b'region', on_delete=django.db.models.deletion.CASCADE, to='bfrs.District'),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='duty_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='init_duty_officer', to=settings.AUTH_USER_MODEL, verbose_name=b'Duty Officer'),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='field_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='init_field_officer', to=settings.AUTH_USER_MODEL, verbose_name=b'Field Officer'),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='final_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_control', to='bfrs.Agency', verbose_name=b'Final Controlling Agency'),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='first_attack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_attack', to='bfrs.Agency', verbose_name=b'First Attack Agency'),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='init_authorised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='init_auth_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Authorised By'),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='initial_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initial_control', to='bfrs.Agency', verbose_name=b'Initial Controlling Agency'),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='modifier',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_bushfire_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.Region'),
        ),
        migrations.AddField(
            model_name='attendingorganisation',
            name='bushfire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attending_organisations', to='bfrs.Bushfire'),
        ),
        migrations.AddField(
            model_name='attendingorganisation',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bfrs.Organisation'),
        ),
        migrations.AddField(
            model_name='areaburnt',
            name='bushfire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_burnt', to='bfrs.Bushfire'),
        ),
        migrations.AddField(
            model_name='areaburnt',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_types', to='bfrs.FuelType'),
        ),
        migrations.AddField(
            model_name='areaburnt',
            name='tenure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenures', to='bfrs.Tenure'),
        ),
        migrations.AddField(
            model_name='aerialforces',
            name='bushfire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aerial_forces', to='bfrs.Bushfire'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.ActivityType'),
        ),
        migrations.AddField(
            model_name='activity',
            name='bushfire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='bfrs.Bushfire'),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set([('bushfire', 'response')]),
        ),
        migrations.AlterUniqueTogether(
            name='publicdamage',
            unique_together=set([('bushfire', 'damage_type', 'fuel_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='privatedamage',
            unique_together=set([('bushfire', 'damage_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='groundforces',
            unique_together=set([('bushfire', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='firebehaviour',
            unique_together=set([('bushfire', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='bushfire',
            unique_together=set([('district', 'incident_no')]),
        ),
        migrations.AlterUniqueTogether(
            name='attendingorganisation',
            unique_together=set([('bushfire', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='areaburnt',
            unique_together=set([('bushfire', 'tenure', 'fuel_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='aerialforces',
            unique_together=set([('bushfire', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set([('bushfire', 'activity')]),
        ),
    ]
