# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-28 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bushfire',
            old_name='final_area',
            new_name='area',
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='report_status',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Initial'), (2, b'Initial Authorised'), (3, b'Draft Final'), (4, b'Final Authorised'), (5, b'Draft Review'), (6, b'Reviewed')], default=1, editable=False),
        ),
    ]
