# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-04 06:24
from __future__ import unicode_literals

from django.db import migrations
from bfrs.utils import create_view, create_final_view, create_fireboundary_view


class Migration(migrations.Migration):

    def run_create_view(apps, schema_editor):
        """ from https://docs.djangoproject.com/en/1.10/topics/migrations/ """
        create_view()
        create_final_view()
        create_fireboundary_view()

    dependencies = [
        ('bfrs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(run_create_view),
    ]
