# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaburnt',
            name='area',
        ),
        migrations.RemoveField(
            model_name='areaburnt',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='bushfire',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='bushfire',
            name='tenure',
        ),
    ]
