# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-02 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bushfire',
            name='sss_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Spatial Support System ID'),
        ),
    ]
