# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-16 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bushfire',
            name='final_snapshot',
            field=models.TextField(blank=True, null=True),
        ),
    ]
