# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-04 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0002_create_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='bushfire',
            name='reporting_year',
            field=models.PositiveSmallIntegerField(default=2016, verbose_name=b'Reporting Year'),
        ),
    ]
