# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-25 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0002_create_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebehaviour',
            name='flame_height',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name=b'Flame height (m)'),
        ),
        migrations.AlterField(
            model_name='firebehaviour',
            name='ros',
            field=models.PositiveSmallIntegerField(verbose_name=b'ROS (m/h)'),
        ),
    ]
