# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-03 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0002_bushfire_sss_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bushfire',
            name='report_status',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Initial'), (2, b'Initial Authorised'), (3, b'Final'), (4, b'Final Authorised')], default=1, editable=False),
        ),
    ]
