# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-02 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0002_create_view'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='damagetype',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='injurytype',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['id']},
        ),
    ]
