# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0002_auto_20170228_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cause',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tenure',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='bushfire',
            name='cause_state',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Known'), (2, b'Possible')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bushfire',
            name='other_tenure',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Other Tenure'),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='tenure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bfrs.Tenure'),
            preserve_default=False,
        ),
    ]
