# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0002_auto_20170131_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bushfire',
            old_name='poly',
            new_name='fire_boundary',
        ),
        migrations.RenameField(
            model_name='bushfire',
            old_name='point',
            new_name='origin_point',
        ),
        migrations.AddField(
            model_name='bushfire',
            name='grid',
            field=models.TextField(blank=True, null=True, verbose_name=b'Lat/Long, MGA, FD Grid'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='dfes_incident_no',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=b'DFES Incident No.'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='incident_no',
            field=models.PositiveIntegerField(verbose_name=b'Fire Incident No.'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='job_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=b'job Code'),
        ),
        migrations.RemoveField(
            model_name='bushfire',
            name='coord_type',
        ),
        migrations.RemoveField(
            model_name='bushfire',
            name='fd_letter',
        ),
        migrations.RemoveField(
            model_name='bushfire',
            name='fd_number',
        ),
        migrations.RemoveField(
            model_name='bushfire',
            name='fd_tenths',
        ),
        migrations.RemoveField(
            model_name='bushfire',
            name='lat_decimal',
        ),
        migrations.RemoveField(
            model_name='bushfire',
            name='lat_degrees',
        ),
        migrations.RemoveField(
            model_name='bushfire',
            name='lat_minutes',
        ),
        migrations.RemoveField(
            model_name='bushfire',
            name='lon_decimal',
        ),
        migrations.RemoveField(
            model_name='bushfire',
            name='lon_degrees',
        ),
        migrations.RemoveField(
            model_name='bushfire',
            name='lon_minutes',
        ),
        migrations.RemoveField(
            model_name='bushfire',
            name='mga_easting',
        ),
        migrations.RemoveField(
            model_name='bushfire',
            name='mga_northing',
        ),
        migrations.RemoveField(
            model_name='bushfire',
            name='mga_zone',
        ),
        migrations.AlterUniqueTogether(
            name='bushfire',
            unique_together=set([('district', 'incident_no')]),
        ),
    ]
