# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0003_auto_20170221_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bushfire',
            name='dispatch_pw_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Dispatch - P&W'),
        ),
    ]
