# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-11 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):


    dependencies = [
        ('bfrs', '0003_auto_20170825_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bushfire',
            name='offence_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name=b'Police Offence No.'),
        ),
        migrations.AlterField(
            model_name='bushfiresnapshot',
            name='offence_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name=b'Police Offence No.'),
        ),
    ]
