# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-29 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0003_auto_20170524_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bushfire',
            name='assistance_details',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='communications',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name=b'Communication'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='other_info',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name=b'Other Information'),
        ),
    ]
