# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-05 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0003_bushfire_reporting_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='bushfire',
            name='fire_not_found',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='invalid_details',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Reason for invalidating'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='report_status',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Initial'), (2, b'Initial Authorised'), (3, b'Draft Final'), (4, b'Final Authorised'), (5, b'Draft Review'), (6, b'Reviewed'), (7, b'Invalidated'), (8, b'Missing Final')], default=1, editable=False),
        ),
    ]
