# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-03 07:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bfrs', '0003_auto_20170502_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('snapshot', models.TextField()),
                ('auth_type', models.CharField(max_length=12, verbose_name=b'Authorisation: Initial/Final/Review')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='dispatch_pw',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Yes'), (2, b'No')], null=True),
        ),
        migrations.AddField(
            model_name='snapshothistory',
            name='bushfire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_history', to='bfrs.Bushfire'),
        ),
        migrations.AddField(
            model_name='snapshothistory',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_snapshothistory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='snapshothistory',
            name='modifier',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_snapshothistory_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
