# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-07 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0003_auto_20170302_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bushfire',
            name='arrival_area',
        ),
    ]
