# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-11 02:51
from __future__ import unicode_literals

from django.db import migrations, models
from bfrs.sql_views import create_bushfirelist_view, create_bushfire_view, create_final_view, create_fireboundary_view, drop_view, drop_final_view, drop_fireboundary_view


class Migration(migrations.Migration):

    def run_drop_view(apps, schema_editor):
        drop_view()
        drop_bushfirelist_view()
        drop_final_view()
        drop_fireboundary_view()
        

    def run_create_view(apps, schema_editor):
        create_view()
        create_bushfirelist_view()
        create_final_view()
        create_fireboundary_view()


    dependencies = [
        ('bfrs', '0003_auto_20170825_1234'),
    ]

    operations = [
        migrations.RunPython(run_drop_view),
        migrations.AlterField(
            model_name='bushfire',
            name='offence_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name=b'Police Offence No.'),
        ),
        migrations.AlterField(
            model_name='bushfiresnapshot',
            name='offence_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name=b'Police Offence No.'),
        ),
        migrations.RunPython(run_create_view),
    ]
