# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0003_bushfire_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bushfire',
            name='year',
            field=models.PositiveIntegerField(default=2016, verbose_name=b'Year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='report_status',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Initial'), (2, b'Final'), (3, b'Final Authorised')], default=1, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='bushfire',
            unique_together=set([('year', 'district', 'incident_no')]),
        ),
    ]
