# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0003_auto_20170201_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bushfire',
            name='grid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Lat/Long, MGA, FD Grid'),
        ),
    ]
