# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0004_auto_20161214_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendingorganisation',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bfrs.Organisation'),
        ),
    ]
