# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 07:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0004_auto_20170208_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bushfire',
            name='year',
            field=models.PositiveIntegerField(default=2016, validators=[django.core.validators.MinValueValidator(2016)], verbose_name=b'Year'),
        ),
    ]
