# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 03:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0004_auto_20170405_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelBehaviour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ros', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'ROS (m/h)')),
                ('flame_height', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Flame height (m)')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.RemoveField(
            model_name='bushfire',
            name='fuel_type',
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='reporting_year',
            field=models.PositiveSmallIntegerField(blank=True, default=2016, verbose_name=b'Reporting Year'),
        ),
        migrations.AddField(
            model_name='fuelbehaviour',
            name='bushfire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_behaviour', to='bfrs.Bushfire'),
        ),
        migrations.AddField(
            model_name='fuelbehaviour',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.FuelType'),
        ),
        migrations.AlterUniqueTogether(
            name='fuelbehaviour',
            unique_together=set([('bushfire', 'fuel_type')]),
        ),
    ]
