# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-19 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0004_auto_20170911_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bushfire',
            name='dispatch_aerial',
            field=models.NullBooleanField(verbose_name=b'Aerial support requested'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='dispatch_aerial_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Aerial support request date'),
        ),
        migrations.AlterField(
            model_name='bushfiresnapshot',
            name='dispatch_aerial',
            field=models.NullBooleanField(verbose_name=b'Aerial support requested'),
        ),
        migrations.AlterField(
            model_name='bushfiresnapshot',
            name='dispatch_aerial_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Aerial support request date'),
        ),
    ]
