# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-04 04:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0004_auto_20170503_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bushfire',
            name='review_snapshot',
        ),
        migrations.AddField(
            model_name='snapshothistory',
            name='action',
            field=models.CharField(default=1, max_length=12, verbose_name=b'Action Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='firebehaviour',
            name='flame_height',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Flame height (m)'),
        ),
        migrations.AlterField(
            model_name='firebehaviour',
            name='ros',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'ROS (m/h)'),
        ),
    ]
