# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 08:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0005_auto_20170411_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireBehaviour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ros', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'ROS (m/h)')),
                ('flame_height', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Flame height (m)')),
                ('bushfire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_behaviour', to='bfrs.Bushfire')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.FuelType')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='fuelbehaviour',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='fuelbehaviour',
            name='bushfire',
        ),
        migrations.RemoveField(
            model_name='fuelbehaviour',
            name='fuel_type',
        ),
        migrations.DeleteModel(
            name='FuelBehaviour',
        ),
        migrations.AlterUniqueTogether(
            name='firebehaviour',
            unique_together=set([('bushfire', 'fuel_type')]),
        ),
    ]
