# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 05:32
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0005_auto_20170607_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bushfire',
            name='init_authorised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='init_authorised_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Initial Authorised By'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='init_authorised_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Initial Authorised Date'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='origin_point',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT (11 -12)', srid=4326),
            preserve_default=False,
        ),
    ]
