# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-09 02:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0006_auto_20170307_1417'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InjuryFatality',
            new_name='Injury',
        ),
        migrations.AddField(
            model_name='areaburnt',
            name='area',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Area (ha)'),
            preserve_default=False,
        ),
    ]
