# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-14 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0006_auto_20170411_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedbushfire',
            name='linked_bushfire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bfrs.Bushfire'),
        ),
    ]
