# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-14 00:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bfrs', '0006_region_forest_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='bushfire',
            name='fireboundary_uploaded_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='fireboundary_uploaded_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name=b'Date fireboundary uploaded'),
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='fireboundary_uploaded_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='fireboundary_uploaded_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name=b'Date fireboundary uploaded'),
        ),
    ]
