# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0006_auto_20170621_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='bushfire',
            name='final_fire_boundary',
            field=models.BooleanField(default=False),
        ),
    ]
