# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-09 03:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0007_auto_20170309_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damage',
            name='area',
        ),
        migrations.AddField(
            model_name='damage',
            name='number',
            field=models.PositiveSmallIntegerField(default=1.1, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
