# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-29 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0007_bushfire_final_fire_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='bushfire',
            name='damage_unknown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='injury_unknown',
            field=models.BooleanField(default=False),
        ),
    ]
