# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-14 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0007_auto_20170414_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedbushfire',
            name='linked_bushfire',
        ),
    ]
