# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-05 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0008_auto_20170504_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshothistory',
            name='prev_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bfrs.SnapshotHistory'),
        ),
    ]
