# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 06:41
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bfrs', '0008_auto_20170629_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='BushfireSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name=b'Fire Name')),
                ('fire_number', models.CharField(max_length=15, verbose_name=b'Fire Number')),
                ('year', models.PositiveSmallIntegerField(default=2016, verbose_name=b'Financial Year')),
                ('reporting_year', models.PositiveSmallIntegerField(blank=True, default=2016, verbose_name=b'Reporting Year')),
                ('prob_fire_level', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], null=True, verbose_name=b'Probable fire level')),
                ('max_fire_level', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], null=True, verbose_name=b'Maximum fire level')),
                ('media_alert_req', models.NullBooleanField(verbose_name=b'Media Alert Required')),
                ('park_trail_impacted', models.NullBooleanField(verbose_name=b'Park and/or trail potentially impacted')),
                ('cause_state', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Known'), (2, b'Possible')], null=True)),
                ('other_cause', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Other Cause')),
                ('prescribed_burn_id', models.CharField(blank=True, max_length=7, null=True, verbose_name=b'Prescribed Burn ID')),
                ('other_tenure', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Private'), (2, b'Crown')], null=True)),
                ('dfes_incident_no', models.CharField(blank=True, max_length=32, null=True, verbose_name=b'DFES Fire Number')),
                ('job_code', models.CharField(blank=True, max_length=12, null=True, verbose_name=b'Job Code')),
                ('fire_position', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Position of Fire')),
                ('fire_position_override', models.BooleanField(default=False, verbose_name=b'SSS override')),
                ('origin_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('fire_boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text=b'Optional.', null=True, srid=4326)),
                ('fire_not_found', models.BooleanField(default=False)),
                ('fire_monitored_only', models.BooleanField(default=False)),
                ('final_fire_boundary', models.BooleanField(default=False)),
                ('assistance_req', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Yes'), (2, b'No'), (3, b'Unknown')], null=True)),
                ('assistance_details', models.CharField(blank=True, max_length=250, null=True)),
                ('communications', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'Communication')),
                ('other_info', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'Other Information')),
                ('init_authorised_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Initial Authorised Date')),
                ('dispatch_pw', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Yes'), (2, b'No')], null=True)),
                ('dispatch_aerial', models.NullBooleanField()),
                ('dispatch_pw_date', models.DateTimeField(blank=True, null=True, verbose_name=b'P&W Resource dispatched')),
                ('dispatch_aerial_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Aerial support dispatched')),
                ('fire_detected_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Fire Detected')),
                ('initial_snapshot', models.TextField(blank=True, null=True)),
                ('final_snapshot', models.TextField(blank=True, null=True)),
                ('fire_contained_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Fire Contained')),
                ('fire_controlled_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Fire Controlled')),
                ('fire_safe_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Fire Safe')),
                ('other_first_attack', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Other First Attack Agency')),
                ('other_initial_control', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Other Initial Control Agency')),
                ('other_final_control', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Other Final Control Agency')),
                ('arson_squad_notified', models.NullBooleanField(verbose_name=b'Arson Squad Notified')),
                ('investigation_req', models.NullBooleanField(verbose_name=b'Investigation Required')),
                ('offence_no', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'Police Offence No.')),
                ('initial_area', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Area of fire at arrival (ha)')),
                ('initial_area_unknown', models.BooleanField(default=False)),
                ('area', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Final Fire Area (ha)')),
                ('area_limit', models.BooleanField(default=False, verbose_name=b'Area < 2ha')),
                ('time_to_control', models.DurationField(blank=True, null=True, verbose_name=b'Time to Control')),
                ('fire_behaviour_unknown', models.BooleanField(default=False)),
                ('damage_unknown', models.BooleanField(default=False)),
                ('injury_unknown', models.BooleanField(default=False)),
                ('authorised_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Authorised Date')),
                ('reviewed_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Reviewed Date')),
                ('report_status', models.PositiveSmallIntegerField(choices=[(1, b'Initial'), (2, b'Initial Authorised'), (3, b'Final Authorised'), (4, b'Reviewed'), (5, b'Invalidated'), (6, b'Missing Final')], default=1, editable=False)),
                ('sss_data', models.TextField(blank=True, null=True, verbose_name=b'SSS REST Api Dict')),
                ('archive', models.BooleanField(default=False, verbose_name=b'Archive report')),
                ('invalid_details', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Reason for invalidating')),
                ('snapshot_type', models.PositiveSmallIntegerField(choices=[(1, b'Initial'), (2, b'Final')])),
                ('authorised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfiresnapshot_authorised_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Authorised By')),
                ('cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bfrs.Cause')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_bushfiresnapshot_created', to=settings.AUTH_USER_MODEL)),
                ('district', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'region', chained_model_field=b'region', on_delete=django.db.models.deletion.CASCADE, to='bfrs.District')),
                ('duty_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfiresnapshot_init_duty_officer', to=settings.AUTH_USER_MODEL, verbose_name=b'Duty Officer')),
                ('field_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfiresnapshot_init_field_officer', to=settings.AUTH_USER_MODEL, verbose_name=b'Field Officer')),
                ('final_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfiresnapshot_final_control', to='bfrs.Agency', verbose_name=b'Final Controlling Agency')),
                ('first_attack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfiresnapshot_first_attack', to='bfrs.Agency', verbose_name=b'First Attack Agency')),
                ('init_authorised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfiresnapshot_init_authorised_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Initial Authorised By')),
                ('initial_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfiresnapshot_initial_control', to='bfrs.Agency', verbose_name=b'Initial Controlling Agency')),
                ('modifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_bushfiresnapshot_modified', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.Region')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfiresnapshot_reviewed_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Reviewed By')),
                ('tenure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bfrs.Tenure')),
                ('valid_bushfire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfiresnapshot_invalidated', to='bfrs.BushfireSnapshot')),
            ],
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='authorised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfire_authorised_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Authorised By'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='duty_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfire_init_duty_officer', to=settings.AUTH_USER_MODEL, verbose_name=b'Duty Officer'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='field_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfire_init_field_officer', to=settings.AUTH_USER_MODEL, verbose_name=b'Field Officer'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='final_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfire_final_control', to='bfrs.Agency', verbose_name=b'Final Controlling Agency'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='first_attack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfire_first_attack', to='bfrs.Agency', verbose_name=b'First Attack Agency'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='init_authorised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfire_init_authorised_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Initial Authorised By'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='initial_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfire_initial_control', to='bfrs.Agency', verbose_name=b'Initial Controlling Agency'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfire_reviewed_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Reviewed By'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='valid_bushfire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfire_invalidated', to='bfrs.Bushfire'),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='bfrs.BushfireSnapshot'),
        ),
        migrations.AlterUniqueTogether(
            name='bushfiresnapshot',
            unique_together=set([('district', 'year', 'fire_number', 'snapshot_type')]),
        ),
    ]
