# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-14 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0008_remove_linkedbushfire_linked_bushfire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedbushfire',
            name='bushfire',
        ),
        migrations.RemoveField(
            model_name='linkedbushfire',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='linkedbushfire',
            name='modifier',
        ),
        migrations.AddField(
            model_name='bushfire',
            name='linked_bushfire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked', to='bfrs.Bushfire'),
        ),
        migrations.DeleteModel(
            name='LinkedBushfire',
        ),
    ]
