# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-20 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0008_auto_20180315_1014'),
    ]

    def forwards(apps, schema_editor):
        init_data = [
            ("AN"    , "Anecdotal (+/- 1 km)"),
            ("BIP"   , "Buffered Ignition Point"),
            ("HIM"   , "Historic maps digitized (+/- 500 m)"),
            ("MM"    , "Mud map (+/- 500 m)"),
            ("RFM"   , "Reference map or photo (50 k) (+/- 250 m)"),
            ("FWGPS" , "Fixed Wing GPS capture (+/- 100m)"),
            ("HCGPS" , "Helicopter GPS capture (+/- 50m)"),
            ("GGPS"  , "Ground GPS capture"),
            ("GPSND" , "GPS - Non-Differential (+/- 5-10 m)"),
            ("GPSD"  , "GPS - Differential (+/- 2-5 m)"),
            ("RS1000", "Remote Sensing, spatial resolution 1000 meters (NOAA)"),
            ("RS500" , "Remote Sensing, spatial resolution 500 meters (MODIS)"),
            ("RS30"  , "Remote Sensing, spatial resolution 30 meters (Landsat)"),
            ("RS25"  , "Remote Sensing, spatial resolution 25 meters (Landsat)"),
            ("999"   , "Unknown")
        ]

        CaptureMethod = apps.get_model('bfrs', 'CaptureMethod')
        CaptureMethod.objects.bulk_create(CaptureMethod(code=o[0],desc=o[1]) for o in init_data)


    operations = [
        migrations.CreateModel(
            name='CaptureMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('desc', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop)
    ]
