# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0009_auto_20170704_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bushfire',
            name='final_snapshot',
        ),
        migrations.RemoveField(
            model_name='bushfire',
            name='initial_snapshot',
        ),
        migrations.RemoveField(
            model_name='bushfiresnapshot',
            name='final_snapshot',
        ),
        migrations.RemoveField(
            model_name='bushfiresnapshot',
            name='initial_snapshot',
        ),
    ]
