# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-14 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0009_auto_20170414_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bushfire',
            name='linked_bushfire',
        ),
        migrations.AddField(
            model_name='bushfire',
            name='valid_bushfire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invalidated', to='bfrs.Bushfire'),
        ),
    ]
