# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-10 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0009_auto_20170309_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='bushfire',
            name='park_trail_impacted',
            field=models.BooleanField(default=False, verbose_name=b'Park and/or trail potentially impacted'),
        ),
    ]
