# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-19 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0010_auto_20170414_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bushfire',
            name='job_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name=b'Job Code'),
        ),
    ]
