# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0010_auto_20170704_1448'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bushfiresnapshot',
            unique_together=set([]),
        ),
    ]
