# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-21 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0010_auto_20180521_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bushfire',
            name='capturemethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bfrs.CaptureMethod'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='other_capturemethod',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name=b'Other Capture Methdod'),
        ),
        migrations.AlterField(
            model_name='bushfiresnapshot',
            name='capturemethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bfrs.CaptureMethod'),
        ),
        migrations.AlterField(
            model_name='bushfiresnapshot',
            name='other_capturemethod',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name=b'Other Capture Methdod'),
        ),
    ]
