# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0011_auto_20170705_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bushfire',
            name='snapshot',
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='bushfire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='bfrs.Bushfire'),
            preserve_default=False,
        ),
    ]
