# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-21 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0011_auto_20170419_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='bushfire',
            name='review_snapshot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='report_status',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Initial'), (2, b'Initial Authorised'), (3, b'Final Authorised'), (4, b'Reviewed'), (5, b'Invalidated'), (6, b'Missing Final')], default=1, editable=False),
        ),
    ]
