# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-11 02:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0011_auto_20170505_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebehaviour',
            name='flame_height',
            field=models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Flame height (m)'),
        ),
        migrations.AlterField(
            model_name='firebehaviour',
            name='ros',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'ROS (m/h)'),
        ),
    ]
