# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0012_auto_20170705_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='action',
            field=models.CharField(default=1, max_length=50, verbose_name=b'Action Type'),
            preserve_default=False,
        ),
    ]
