# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-11 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0012_auto_20170511_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bushfire',
            name='dfes_incident_no',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name=b'DFES Fire Number'),
        ),
    ]
