# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-27 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0012_auto_20170421_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='bushfire',
            name='sss_data',
            field=models.TextField(blank=True, null=True, verbose_name=b'SSS REST Api Dict'),
        ),
    ]
