# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-16 08:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0012_auto_20170314_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaburnt',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Name'),
        ),
        migrations.AddField(
            model_name='areaburnt',
            name='other',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Other tenure'),
        ),
        migrations.AlterField(
            model_name='areaburnt',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Area (ha)'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='dispatch_aerial_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Aerial support dispatched'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='dispatch_pw_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'P&W Resource dispatched'),
        ),
        migrations.AlterField(
            model_name='tenure',
            name='name',
            field=models.CharField(max_length=200, verbose_name=b'Tenure category'),
        ),
    ]
