# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-09 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0012_auto_20180808_1548'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='areaburntsnapshot',
            unique_together=set([('tenure', 'snapshot')]),
        ),
        migrations.AlterUniqueTogether(
            name='bushfirepropertysnapshot',
            unique_together=set([('snapshot', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='damagesnapshot',
            unique_together=set([('damage_type', 'snapshot')]),
        ),
        migrations.AlterUniqueTogether(
            name='injurysnapshot',
            unique_together=set([('injury_type', 'snapshot')]),
        ),
    ]
