# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-17 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0013_auto_20170511_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='snapshothistory',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
    ]
