# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-28 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0013_bushfire_sss_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bushfire',
            name='assistance_req',
        ),
        migrations.RemoveField(
            model_name='bushfire',
            name='dispatch_pw',
        ),
        migrations.RemoveField(
            model_name='bushfire',
            name='other_tenure',
        ),
    ]
