# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0013_bushfiresnapshot_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshothistory',
            name='bushfire',
        ),
        migrations.RemoveField(
            model_name='snapshothistory',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='snapshothistory',
            name='modifier',
        ),
        migrations.RemoveField(
            model_name='snapshothistory',
            name='prev_snapshot',
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='json_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SnapshotHistory',
        ),
    ]
