# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-17 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0013_auto_20170316_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaburnt',
            name='name',
        ),
    ]
