# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-27 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0013_auto_20180809_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bushfire',
            name='fire_bombing_req',
        ),
        migrations.RemoveField(
            model_name='bushfiresnapshot',
            name='fire_bombing_req',
        ),
    ]
