# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-20 07:11
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bfrs', '0014_remove_areaburnt_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialDataHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('origin_point', django.contrib.gis.db.models.fields.PointField(blank=True, help_text=b'Optional.', null=True, srid=4326)),
                ('fire_boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text=b'Optional.', null=True, srid=4326)),
                ('area_burnt', models.TextField(blank=True, null=True, verbose_name=b'Area Burnt')),
                ('bushfire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spatial_data_history', to='bfrs.Bushfire')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_spatialdatahistory_created', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_spatialdatahistory_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
