# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-03 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0014_auto_20180827_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='bushfire',
            name='origin_point_grid',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name=b'Point of Origin (GRID)'),
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='origin_point_grid',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name=b'Point of Origin (GRID)'),
        ),
    ]
