# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0015_auto_20170713_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagesnapshot',
            name='snapshot_type',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Initial'), (2, b'Final')], default=1),
            preserve_default=False,
        ),
    ]
