# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-22 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0015_auto_20170522_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='bushfire',
            name='prescribed_burn_id',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name=b'Prescribed Burn ID'),
        ),
    ]
