# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-01 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0015_auto_20170428_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fueltype',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='bushfire',
            name='fire_behaviour_unknown',
            field=models.BooleanField(default=False),
        ),
    ]
