# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-21 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0015_spatialdatahistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialdatahistory',
            name='tenure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tenure_history', to='bfrs.Tenure'),
            preserve_default=False,
        ),
    ]
