# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 08:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0016_damagesnapshot_snapshot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagesnapshot',
            name='damage_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bfrs.DamageType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='damagesnapshot',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
