# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-23 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0016_spatialdatahistory_tenure'),
    ]

    operations = [
        migrations.AddField(
            model_name='bushfire',
            name='fire_number',
            field=models.CharField(default=1, max_length=15, verbose_name=b'Fire Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='year',
            field=models.PositiveSmallIntegerField(default=2016, verbose_name=b'Financial Year'),
        ),
#        migrations.RemoveField(
#            model_name='bushfire',
#            name='incident_no',
#        ),
        migrations.AlterUniqueTogether(
            name='bushfire',
            unique_together=set([('district', 'year', 'fire_number')]),
        ),
    ]
