# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-23 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0017_auto_20170323_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bushfire',
            name='incident_no',
        ),
    ]
