# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-14 02:56
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bfrs', '0018_auto_20170714_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaBurntSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Area (ha)')),
                ('snapshot_type', models.PositiveSmallIntegerField(choices=[(1, b'Initial'), (2, b'Final')])),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_areaburntsnapshot_created', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_areaburntsnapshot_modified', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenures_burnt_snapshot', to='bfrs.BushfireSnapshot')),
                ('tenure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areaburntsnapshot_tenures', to='bfrs.Tenure')),
            ],
        ),
        migrations.CreateModel(
            name='FireBehaviourSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ros', models.PositiveSmallIntegerField(verbose_name=b'ROS (m/h)')),
                ('flame_height', models.DecimalField(decimal_places=1, max_digits=6, verbose_name=b'Flame height (m)')),
                ('snapshot_type', models.PositiveSmallIntegerField(choices=[(1, b'Initial'), (2, b'Final')])),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_firebehavioursnapshot_created', to=settings.AUTH_USER_MODEL)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.FuelType')),
                ('modifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_firebehavioursnapshot_modified', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_behaviour_snapshot', to='bfrs.BushfireSnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='InjurySnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('snapshot_type', models.PositiveSmallIntegerField(choices=[(1, b'Initial'), (2, b'Final')])),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_injurysnapshot_created', to=settings.AUTH_USER_MODEL)),
                ('injury_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.InjuryType')),
                ('modifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_injurysnapshot_modified', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injury_snapshot', to='bfrs.BushfireSnapshot')),
            ],
        ),
        migrations.AlterField(
            model_name='areaburnt',
            name='tenure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areaburnt_tenures', to='bfrs.Tenure'),
        ),
        migrations.AlterField(
            model_name='damagesnapshot',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_snapshot', to='bfrs.BushfireSnapshot'),
        ),
        migrations.AlterUniqueTogether(
            name='injurysnapshot',
            unique_together=set([('injury_type', 'snapshot', 'snapshot_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='firebehavioursnapshot',
            unique_together=set([('fuel_type', 'snapshot', 'snapshot_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='areaburntsnapshot',
            unique_together=set([('tenure', 'snapshot', 'snapshot_type')]),
        ),
    ]
