# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-08 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0018_tenuremapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenure',
            name='report_group',
            field=models.CharField(default=b'', max_length=32, verbose_name=b'Tenure category report group'),
        ),
        migrations.AddField(
            model_name='tenure',
            name='report_name',
            field=models.CharField(default=b'', max_length=200, verbose_name=b'Tenure category report name'),
        ),
        migrations.AddField(
            model_name='tenure',
            name='report_order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name=b'Tenure category report group'),
        ),
    ]
