# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-24 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0018_remove_bushfire_incident_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bushfire',
            name='area_unknown',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='arson_squad_notified',
            field=models.BooleanField(verbose_name=b'Arson Squad Notified'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='assistance_req',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bfrs.Cause'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='cause_state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Known'), (2, b'Possible')], null=True),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='dispatch_aerial',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='dispatch_pw',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='fire_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='fire_not_found',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Fuel Type'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='investigation_req',
            field=models.BooleanField(verbose_name=b'Investigation Required'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='media_alert_req',
            field=models.BooleanField(verbose_name=b'Media Alert Required'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='park_trail_impacted',
            field=models.BooleanField(verbose_name=b'Park and/or trail potentially impacted'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='tenure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bfrs.Tenure'),
        ),
    ]
