# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0019_auto_20170714_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='bushfire',
            name='other_field_officer',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name=b'Other Field Officer Name'),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='other_field_officer_agency',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name=b'Other Field Officer Agency'),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='other_field_officer_phone',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name=b'Other Field Officer Phone'),
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='other_field_officer',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name=b'Other Field Officer Name'),
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='other_field_officer_agency',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name=b'Other Field Officer Agency'),
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='other_field_officer_phone',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name=b'Other Field Officer Phone'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='fire_safe_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Fire inactive'),
        ),
        migrations.AlterField(
            model_name='bushfiresnapshot',
            name='fire_safe_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Fire inactive'),
        ),
    ]
