# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-24 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0019_auto_20170324_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bushfire',
            name='fire_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1),
        ),
    ]
