# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-08 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0020_auto_20190508_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='report_name',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='cause',
            name='report_order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name=b'order in annual report'),
        ),
        migrations.AlterField(
            model_name='tenure',
            name='report_group_order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name=b'group order in annual report'),
        ),
        migrations.AlterField(
            model_name='tenure',
            name='report_order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name=b'order in annual report'),
        ),
    ]
