# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-24 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0020_auto_20170324_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bushfire',
            name='arson_squad_notified',
            field=models.NullBooleanField(verbose_name=b'Arson Squad Notified'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='assistance_req',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='dispatch_aerial',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='dispatch_pw',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='fire_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)]),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='fire_not_found',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='investigation_req',
            field=models.NullBooleanField(verbose_name=b'Investigation Required'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='media_alert_req',
            field=models.NullBooleanField(verbose_name=b'Media Alert Required'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='park_trail_impacted',
            field=models.NullBooleanField(verbose_name=b'Park and/or trail potentially impacted'),
        ),
    ]
