# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-27 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0021_auto_20190508_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bushfire',
            name='other_tenure',
        ),
        migrations.RemoveField(
            model_name='bushfiresnapshot',
            name='other_tenure',
        ),
    ]
