# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-26 03:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0021_auto_20170725_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='bushfire',
            name='other_area',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Other Area (ha)'),
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='other_area',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Other Area (ha)'),
        ),
    ]
