# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-24 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0022_auto_20170324_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bushfire',
            name='fire_not_found',
            field=models.BooleanField(default=True),
        ),
    ]
