# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0022_auto_20170726_1158'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='firebehaviour',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='firebehaviour',
            name='bushfire',
        ),
        migrations.RemoveField(
            model_name='firebehaviour',
            name='fuel_type',
        ),
        migrations.AlterUniqueTogether(
            name='firebehavioursnapshot',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='firebehavioursnapshot',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='firebehavioursnapshot',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='firebehavioursnapshot',
            name='modifier',
        ),
        migrations.RemoveField(
            model_name='firebehavioursnapshot',
            name='snapshot',
        ),
        migrations.RemoveField(
            model_name='bushfire',
            name='fire_behaviour_unknown',
        ),
        migrations.RemoveField(
            model_name='bushfiresnapshot',
            name='fire_behaviour_unknown',
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='reporting_year',
            field=models.PositiveSmallIntegerField(blank=True, default=2017, verbose_name=b'Reporting Year'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='year',
            field=models.PositiveSmallIntegerField(default=2017, verbose_name=b'Financial Year'),
        ),
        migrations.AlterField(
            model_name='bushfiresnapshot',
            name='reporting_year',
            field=models.PositiveSmallIntegerField(blank=True, default=2017, verbose_name=b'Reporting Year'),
        ),
        migrations.AlterField(
            model_name='bushfiresnapshot',
            name='year',
            field=models.PositiveSmallIntegerField(default=2017, verbose_name=b'Financial Year'),
        ),
        migrations.DeleteModel(
            name='FireBehaviour',
        ),
        migrations.DeleteModel(
            name='FireBehaviourSnapshot',
        ),
    ]
