# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-28 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0022_auto_20190527_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenuremapping',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name=b'Tenure sub category'),
        ),
    ]
