# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-28 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0023_auto_20170324_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaburnt',
            name='other',
        ),
        migrations.RemoveField(
            model_name='bushfire',
            name='area_unknown',
        ),
        migrations.RemoveField(
            model_name='bushfire',
            name='fire_not_found',
        ),
        migrations.RemoveField(
            model_name='bushfire',
            name='sss_id',
        ),
        migrations.AddField(
            model_name='bushfire',
            name='area_limit',
            field=models.BooleanField(default=False, verbose_name=b'Area < 2ha'),
        ),
    ]
