# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-06-25 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0023_auto_20190528_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bushfiresnapshot',
            name='action',
            field=models.CharField(max_length=100, verbose_name=b'Action Type'),
        ),
    ]
