# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-28 06:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0024_auto_20170328_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedBushfire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_id', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created', models.DateTimeField(verbose_name=b'Created date')),
            ],
        ),
        migrations.AddField(
            model_name='bushfire',
            name='invalid',
            field=models.BooleanField(default=False, verbose_name=b'Invalidate report'),
        ),
        migrations.AddField(
            model_name='linkedbushfire',
            name='bushfire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked', to='bfrs.Bushfire'),
        ),
    ]
