# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-09-16 04:33
from __future__ import unicode_literals

import bfrs.base
import bfrs.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bfrs', '0024_auto_20190625_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('custom_tag', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Custom Descriptor')),
                ('document', models.FileField(upload_to=bfrs.models.document_path, verbose_name=b'Document')),
                ('document_created', models.DateTimeField(verbose_name=b'Created on')),
                ('archived', models.BooleanField(default=False)),
                ('archivedon', models.DateTimeField(editable=False, null=True, verbose_name=b'Archived on')),
                ('archivedby', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Archived By')),
            ],
            bases=(bfrs.base.DictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name=b'Document Category')),
                ('archived', models.BooleanField(default=False)),
                ('archivedon', models.DateTimeField(editable=False, null=True, verbose_name=b'Archived on')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('archivedby', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Archived By')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_documentcategory_created', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_documentcategory_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
            bases=(bfrs.base.DictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name=b'Document Tag')),
                ('archived', models.BooleanField(default=False)),
                ('archivedon', models.DateTimeField(editable=False, null=True, verbose_name=b'Archived on')),
                ('archivedby', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Archived By')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bfrs.DocumentCategory')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_documenttag_created', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_documenttag_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(bfrs.base.DictMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='reporting_year',
            field=models.PositiveSmallIntegerField(blank=True, default=bfrs.models.current_finyear, verbose_name=b'Reporting Year'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='year',
            field=models.PositiveSmallIntegerField(default=bfrs.models.current_finyear, verbose_name=b'Financial Year'),
        ),
        migrations.AlterField(
            model_name='bushfiresnapshot',
            name='reporting_year',
            field=models.PositiveSmallIntegerField(blank=True, default=bfrs.models.current_finyear, verbose_name=b'Reporting Year'),
        ),
        migrations.AlterField(
            model_name='bushfiresnapshot',
            name='year',
            field=models.PositiveSmallIntegerField(default=bfrs.models.current_finyear, verbose_name=b'Financial Year'),
        ),
        migrations.AddField(
            model_name='document',
            name='bushfire',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bfrs.Bushfire', verbose_name=b'Bushfire'),
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.DocumentCategory', verbose_name=b'Document Category'),
        ),
        migrations.AddField(
            model_name='document',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_document_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='modifier',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_document_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.DocumentTag', verbose_name=b'Document Tag'),
        ),
        migrations.AddField(
            model_name='document',
            name='upload_bushfire',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='bfrs.Bushfire', verbose_name=b'Upload Bushfire'),
        ),
    ]
