# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0024_auto_20170803_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bushfire',
            name='fire_number',
            field=models.CharField(max_length=15, unique=True, verbose_name=b'Fire Number'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='sss_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name=b'Unique SSS ID'),
        ),
        migrations.AlterField(
            model_name='bushfiresnapshot',
            name='sss_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Unique SSS ID'),
        ),
        migrations.AlterUniqueTogether(
            name='bushfire',
            unique_together=set([]),
        ),
    ]
