# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-06-26 01:08
from __future__ import unicode_literals

import bfrs.base
import bfrs.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bfrs', '0024_auto_20190625_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(editable=False, upload_to=bfrs.models.document_path, verbose_name=b'Document')),
                ('comment', models.TextField(null=True, verbose_name=b'Comment')),
                ('deleted', models.BooleanField(default=False)),
                ('bushfire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bfrs.Bushfire', verbose_name=b'Bushfire')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_document_created', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_document_modified', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(bfrs.base.DictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DocumentSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('snapshot_type', models.PositiveSmallIntegerField(choices=[(1, b'Initial'), (2, b'Final')])),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('snapshot_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('damage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.DamageType')),
                ('modifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='modifier', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_snapshot', to='bfrs.BushfireSnapshot')),
                ('snapshot_creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name=b'Title')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_documenttitle_created', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bfrs_documenttitle_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(bfrs.base.DictMixin, models.Model),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfrs.DocumentTitle', verbose_name=b'Document Title'),
        ),
        migrations.AddField(
            model_name='document',
            name='upload_bushfire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='bfrs.Bushfire', verbose_name=b'Upload Bushfire'),
        ),
    ]
