# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-06-26 23:55
from __future__ import unicode_literals

import bfrs.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bfrs', '0025_auto_20190626_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='deleteby',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedby', to=settings.AUTH_USER_MODEL, verbose_name=b'Deleted By'),
        ),
        migrations.AddField(
            model_name='document',
            name='deleteon',
            field=models.DateTimeField(editable=False, null=True, verbose_name=b'Deleted on'),
        ),
        migrations.AlterField(
            model_name='document',
            name='bushfire',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bfrs.Bushfire', verbose_name=b'Bushfire'),
        ),
        migrations.AlterField(
            model_name='document',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name=b'Comment'),
        ),
        migrations.AlterField(
            model_name='document',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=bfrs.models.document_path, verbose_name=b'Document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload_bushfire',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='bfrs.Bushfire', verbose_name=b'Upload Bushfire'),
        ),
        migrations.AlterField(
            model_name='documentsnapshot',
            name='snapshot',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='documents_snapshot', to='bfrs.BushfireSnapshot'),
        ),
        migrations.AlterField(
            model_name='documentsnapshot',
            name='snapshot_type',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Initial'), (2, b'Final')], editable=False),
        ),
        migrations.AlterField(
            model_name='documenttitle',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name=b'Name'),
        ),
    ]
