# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-09-19 03:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0025_auto_20190916_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='documentcategory',
            name='order',
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bfrs.DocumentCategory', verbose_name=b'Document Category'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bfrs.DocumentTag', verbose_name=b'Document Tag'),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='archivedby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Archived By'),
        ),
        migrations.AlterField(
            model_name='documenttag',
            name='archivedby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Archived By'),
        ),
        migrations.AlterUniqueTogether(
            name='documenttag',
            unique_together=set([('category', 'name')]),
        ),
    ]
