# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0025_auto_20170803_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='bushfire',
            name='fb_validation_req',
            field=models.NullBooleanField(verbose_name=b'Fire Boundary Validation Required?'),
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='fb_validation_req',
            field=models.NullBooleanField(verbose_name=b'Fire Boundary Validation Required?'),
        ),
    ]
