# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 08:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bfrs', '0026_auto_20170804_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='bushfire',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfire_reviewed_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Reviewed By'),
        ),
        migrations.AddField(
            model_name='bushfire',
            name='reviewed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Reviewed Date'),
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bushfiresnapshot_reviewed_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Reviewed By'),
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='reviewed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Reviewed Date'),
        ),
    ]
