# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-30 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0026_auto_20170330_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedbushfire',
            name='linked_fire_number',
        ),
        migrations.RemoveField(
            model_name='linkedbushfire',
            name='linked_id',
        ),
        migrations.AddField(
            model_name='linkedbushfire',
            name='linked_bushfire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bfrs.Bushfire'),
            preserve_default=False,
        ),
    ]
