# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-06-27 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0026_auto_20190627_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.CharField(default='', editable=False, max_length=128, verbose_name=b'Document File Name'),
            preserve_default=False,
        ),
    ]
