# Generated by Django 5.2.15 on 2026-06-17 09:03

# Generated by Django 5.2

from django.db import migrations
import os
from django.conf import settings


def load_sql_file(filename):
    file_path = os.path.join(settings.BASE_DIR, 'sqlscripts', filename)
    with open(file_path, 'r') as f:
        return f.read()


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0026_auto_20190919_1114'),
    ]

    operations = [

        migrations.RunSQL("DROP VIEW IF EXISTS bushfirelist_latest;"),

        migrations.RunSQL("DROP VIEW IF EXISTS bfrs_bushfirelist_v;"),

        migrations.RunSQL("""
        CREATE VIEW bfrs_bushfirelist_v AS
        SELECT b.id,
        b.origin_point,
        CASE 
            WHEN b.report_status >= 6 THEN ST_AsGeoJSON(st_envelope(b.fire_boundary))
            ELSE ST_AsGeoJSON(b.fire_boundary)
        END as fire_boundary,
        b.fb_validation_req,
        b.created,
        b.modified,
        b.name,
        b.fire_number,
        b.year,
        b.reporting_year,
        b.prob_fire_level,
        b.max_fire_level,
        CASE WHEN b.media_alert_req IS NULL THEN NULL
             WHEN b.media_alert_req THEN 1
             ELSE 0
        END as media_alert_req,
        CASE WHEN b.park_trail_impacted IS NULL THEN NULL
             WHEN b.park_trail_impacted THEN 1
             ELSE 0
        END as park_trail_impacted,
        b.cause_state,
        b.other_cause,
        b.dfes_incident_no,
        b.job_code,
        b.fire_position,
        b.sss_id,
        CASE WHEN b.fire_position_override IS NULL THEN NULL
             WHEN b.fire_position_override THEN 1
             ELSE 0
        END as fire_position_override,
        CASE WHEN b.fire_not_found IS NULL THEN NULL
             WHEN b.fire_not_found THEN 1
             ELSE 0
        END as fire_not_found,
        b.other_info,
        b.init_authorised_date,
        b.dispatch_pw,
        CASE WHEN b.dispatch_aerial IS NULL THEN NULL
             WHEN b.dispatch_aerial THEN 1
             ELSE 0
        END as dispatch_aerial,
        b.dispatch_pw_date,
        b.dispatch_aerial_date,
        b.fire_detected_date,
        CASE 
            WHEN fire_detected_date IS NULL THEN created
            ELSE fire_detected_date
        END as fire_detected_or_created,
        b.fire_contained_date,
        b.fire_controlled_date,
        b.fire_safe_date,
        b.other_first_attack,
        b.other_initial_control,
        b.other_final_control,
        CASE WHEN b.arson_squad_notified IS NULL THEN NULL
             WHEN b.arson_squad_notified THEN 1
             ELSE 0
        END as arson_squad_notified,
        CASE WHEN b.investigation_req IS NULL THEN NULL
             WHEN b.investigation_req THEN 1
             ELSE 0
        END as investigation_req,
        b.offence_no,
        b.initial_area,
        b.area,
        CASE WHEN b.area_limit IS NULL THEN NULL
             WHEN b.area_limit THEN 1
             ELSE 0
        END as area_limit,
        CASE WHEN b.initial_area_unknown IS NULL THEN NULL
             WHEN b.initial_area_unknown THEN 1
             ELSE 0
        END as initial_area_unknown,
        b.authorised_date,
        b.report_status,
        CASE WHEN b.archive IS NULL THEN NULL
             WHEN b.archive THEN 1
             ELSE 0
        END as archive,
        CASE WHEN b.valid_bushfire_id is null THEN NULL
             ELSE (SELECT report_status FROM bfrs_bushfire WHERE id = b.valid_bushfire_id)
        END as linked_bushfire_status,
        CASE WHEN b.valid_bushfire_id is null THEN NULL
             ELSE (SELECT fire_number FROM bfrs_bushfire WHERE id = b.valid_bushfire_id)
        END as linked_bushfire_number,
        b.authorised_by_id,
        b.cause_id,
        b.creator_id,
        b.district_id,
        b.duty_officer_id,
        b.field_officer_id,
        b.final_control_id,
        b.first_attack_id,
        b.init_authorised_by_id,
        b.initial_control_id,
        b.modifier_id,
        b.region_id,
        b.tenure_id
        FROM bfrs_bushfire b
        WHERE b.archive = false 
        AND (b.report_status < 5 OR b.report_status = 100);
        """),

        migrations.RunSQL(load_sql_file("bushfirelist_latest_view.sql")),
    ]