# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-30 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0027_auto_20170330_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bushfire',
            name='report_status',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Initial'), (2, b'Initial Authorised'), (3, b'Draft Final'), (4, b'Final Authorised'), (5, b'Draft Review'), (6, b'Reviewed'), (7, b'Invalidated')], default=1, editable=False),
        ),
    ]
