# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-15 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0027_auto_20170804_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='bushfire',
            name='origin_point_mga',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Point of Origin (MGA)'),
        ),
        migrations.AddField(
            model_name='bushfiresnapshot',
            name='origin_point_mga',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Point of Origin (MGA)'),
        ),
        migrations.AlterField(
            model_name='bushfire',
            name='other_tenure',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Private'), (2, b'Crown')], null=True, verbose_name=b'Tenure of ignition point (crown/private)'),
        ),
        migrations.AlterField(
            model_name='bushfiresnapshot',
            name='other_tenure',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Private'), (2, b'Crown')], null=True, verbose_name=b'Tenure of ignition point (crown/private)'),
        ),
    ]
