# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-07-24 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0028_auto_20190723_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttitle',
            name='sorting',
            field=models.CharField(editable=False, max_length=64, null=True, verbose_name=b'Used for sorting'),
        ),
    ]
