# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-30 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0028_auto_20170330_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bushfire',
            name='invalid',
        ),
    ]
