# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-08-29 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0029_documenttitle_sorting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttitle',
            options={'ordering': ['sorting']},
        ),
    ]
