# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-30 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0029_remove_bushfire_invalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bushfire',
            name='fire_position_override',
            field=models.BooleanField(default=False, verbose_name=b'SSS override'),
        ),
    ]
