# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-31 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0030_bushfire_fire_position_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='bushfire',
            name='area_unknown',
            field=models.BooleanField(default=False),
        ),
    ]
