# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-31 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfrs', '0032_auto_20170331_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='alias',
        ),
    ]
